### ISSUE TITLE
Re-wrap decrypted message when replying

### ISSUE THREAD

**Issue by tylerburton** [thialfihar/apg#57]
If you receive an encrypted message and decrypt it before replying then the reply should contain the decrypted text (which would then also be re-encrypted by your new message) instead of the original cipher text.

For example:

Alice sends Bob a message:

`-----BEGIN PGP MESSAGE-----`
`... BASE64_CIPHER_TEXT ...`
`-----END PGP MESSAGE-----`

that decrypts to

`-----BEGIN PGP MESSAGE-----`
`... some message ...`
`-----END PGP MESSAGE-----`

Bob replies. When Alice decrypts the reply it should look like this:

`-----BEGIN PGP MESSAGE-----`
`... some reply...`
`>> Message from Bob:`
`>> ... some message ...`
`-----END PGP MESSAGE-----`

Currently APG creates a reply that when decrypted looks like this:

`-----BEGIN PGP MESSAGE-----`
`... some reply...`
`>>-----BEGIN PGP MESSAGE-----`
`>>... BASE64_CIPHER_TEXT ...`
`>>-----END PGP MESSAGE-----`
`-----END PGP MESSAGE-----`

**Comment by alanthehat** [comment]
is this APG or your mail app? 
APG only decrypts or encrypts the text supplied to it by the mailer.

**Comment by tylerburton** [comment]
That is a fair point. I've opened up the issue with k9mail at https://code.google.com/p/k9mail/issues/detail?id=6683 for those interested in following the progress there.
